# Generated by Django 4.1.5 on 2023-01-30 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('comments', models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Время попытки')),
                ('status', models.CharField(choices=[('s', 'Попытка успешна'), ('f', 'Попытка не удалась')], default='f', max_length=1, verbose_name='Статус попытки')),
                ('answer', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ответ почтового сервера')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=150, verbose_name='Тема')),
                ('body', models.CharField(max_length=500, verbose_name='Тело сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время рассылки')),
                ('frequency', models.CharField(choices=[('d', 'Раз в день'), ('w', 'Раз в неделю'), ('m', 'Раз в месяц')], default='w', max_length=1, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('c', 'Создана'), ('s', 'Запущена'), ('f', 'Завершена')], default='c', max_length=1, verbose_name='Статус рассылки')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail_app.message')),
                ('recipient', models.ManyToManyField(to='mail_app.client')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
