# Generated by Django 4.1.5 on 2023-01-30 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0002_mailingattempt_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingattempt',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail_app.mailing'),
        ),
    ]
