# Generated by Django 4.1.7 on 2023-02-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0003_alter_mailingattempt_mailing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
