# Generated by Django 4.1.7 on 2023-02-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0008_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.CharField(max_length=500, verbose_name='Текст сообщения'),
        ),
    ]
